Fix: This object does not have an attribute named "id".
Error: Unsupported attribute

  on .terraform/modules/cloudfront/main.tf line 52, in resource "aws_cloudfront_key_group" "this":
  52:   items = aws_cloudfront_public_key.this[*].id

This object does not have an attribute named "id".